import os
import random
import time
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import firebase_admin
from firebase_admin import credentials, db
import numpy as np
from sklearn.linear_model import LinearRegression
from groq import Groq
import requests
from dotenv import load_dotenv

# --- 1. ENVIRONMENT & CLOUD SETUP ---
load_dotenv() 
groq_api = os.getenv("GROQ_API_KEY") 
tomtom_api = os.getenv("TOMTOM_API_KEY") 

# Fetch secure email credentials from .env
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")
RECEIVER_EMAIL = os.getenv("RECEIVER_EMAIL")

# Initialize Firebase Realtime Database
if not firebase_admin._apps:
    cred = credentials.Certificate("serviceAccountKey.json")
    firebase_admin.initialize_app(cred, {
        'databaseURL': 'https://pharmaguard-iot-default-rtdb.firebaseio.com/'
    })

# Initialize Cloud Clients
client = Groq(api_key=groq_api)
ref = db.reference('medicine_logs')
temp_history = []

# --- 2. EMAIL ALERT SYSTEM ---
def send_email_alert(subject, message_body):
    """Dispatches professional HTML alert emails to stakeholders."""
    if not SENDER_EMAIL or not SENDER_PASSWORD:
        print("⚠️ Email configuration missing. Please verify your .env file.")
        return

    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = subject

    # Professional Responsive HTML Structure
    html = f"""
    <html>
      <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; background-color: #f9f9f9; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 8px; padding: 25px; border-top: 5px solid #d9534f; box-shadow: 0 4px 10px rgba(0,0,0,0.05);">
          <h2 style="color: #d9534f; margin-top: 0;">🚨 PharmaGuard AI Telemetry Alert</h2>
          <p style="color: #666; font-size: 13px;"><strong>Timestamp:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
          <hr style="border: 0; border-top: 1px solid #eee; margin: 15px 0;">
          <div style="font-size: 15px; color: #444; background: #fff5f5; border-left: 4px solid #d9534f; padding: 15px; border-radius: 4px;">
            {message_body}
          </div>
          <br>
          <hr style="border: 0; border-top: 1px solid #eee; margin: 15px 0;">
          <p style="font-size: 11px; color: #999; text-align: center; margin-bottom: 0;">This is an automated telemetry alert generated by the PharmaGuard IoT Edge Node.</p>
        </div>
      </body>
    </html>
    """
    msg.attach(MIMEText(html, 'html'))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())
        print(f"📧 [SYSTEM ALERT] Notification email transmitted successfully to {RECEIVER_EMAIL}!")
    except Exception as e:
        print(f"❌ Critical Mailer Error: {e}")

# --- 3. CORE INTELLIGENCE FUNCTIONS ---
def predict_next_temp():
    """Predicts future temperature using Linear Regression based on history window."""
    if len(temp_history) < 3: 
        return "Analyzing..."
    X = np.array(range(len(temp_history))).reshape(-1, 1)
    y = np.array(temp_history)
    model = LinearRegression().fit(X, y)
    prediction = model.predict([[len(temp_history)]])[0]
    return round(float(prediction), 2)

def get_ai_advice(temp, hum, lid, traffic):
    """Fetches real-time smart logistics advice from Llama-3 with strict pathogen compliance."""
    try:
        prompt = (f"Temp: {temp}C, Humidity: {hum}%, Lid: {lid}, Traffic Conditions: {traffic}. "
                  f"Provide 1-sentence pharmaceutical logistics advice. If Lid is OPEN, explicitly "
                  f"warn about bacterial contamination/pathogen risks based on transport safety standards.")
        
        completion = client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model="llama-3.3-70b-versatile",
            max_tokens=40
        )
        return completion.choices[0].message.content.strip()
    except Exception as e:
        return "AI Agent: Optimization advice momentarily offline."

def get_real_traffic(lat, lon):
    """Evaluates route traffic density using TomTom Flow Segment API."""
    screenshot_mode = "REALTIME"  
    
    if screenshot_mode == "HEAVY":
        return "Heavy Traffic"
    elif screenshot_mode == "MODERATE":
        return "Moderate Jam"

    url = f"https://api.tomtom.com/traffic/services/4/flowSegmentData/absolute/10/json?point={lat},{lon}&key={tomtom_api}"
    try:
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            data = response.json()
            current_speed = data['flowSegmentData']['currentSpeed']
            free_flow_speed = data['flowSegmentData']['freeFlowSpeed']
            ratio = current_speed / free_flow_speed
            
            if ratio > 0.8:
                return "Smooth"
            elif ratio > 0.5:
                return "Moderate Jam"
            else:
                return "Heavy Traffic"
        else:
            return "Smooth"
    except Exception as e:
        return "Smooth"

# --- 4. LIVE MONITORING LOOP ---
print("🚀 PharmaGuard AI: Telemetry Matrix Online & Cloud Integration Stable...")

# Anti-spam flags for loop iterations
heavy_traffic_alert_sent = False
bacterial_alert_sent = False

try:
    while True:
        # Generate Simulated Cold-Chain Telemetry
        temp = round(random.uniform(2.0, 8.0), 2)
        humidity = round(random.uniform(40.0, 60.0), 2)
        lid = "OPEN" if random.random() < 0.05 else "CLOSED"
        shock = round(random.uniform(0.1, 0.9), 2)
        
        # Live tracking for Mohakhali, Dhaka (23.7779, 90.4007)
        traffic = get_real_traffic(23.7779, 90.4007)
        
        # Maintain history window for ML model
        temp_history.append(temp)
        if len(temp_history) > 10: 
            temp_history.pop(0)
        
        prediction = predict_next_temp()
        advice = get_ai_advice(temp, humidity, lid, traffic)
        timestamp = datetime.now().strftime("%H:%M:%S")

        # --- 🚨 DYNAMIC ALERT LOGIC ---
        
        # Trigger 1: Transit Congestion Delay
        if traffic == "Heavy Traffic" and not heavy_traffic_alert_sent:
            email_subject = "⚠️ CRITICAL TRANSIT DELAY: Heavy Congestion Alert!"
            email_body = f"The cold-chain transport node has encountered <b>Heavy Traffic</b> in the Dhaka sector.<br><br><b>Current Temp:</b> {temp}°C.<br><b>Predictive Temp (ML):</b> {prediction}°C.<br><b>Llama-3 Strategy:</b> {advice}"
            send_email_alert(email_subject, email_body)
            heavy_traffic_alert_sent = True 
            
        elif traffic != "Heavy Traffic":
            heavy_traffic_alert_sent = False 

        # Trigger 2 & 3: Container Breach & Bacterial Contamination Risk Analysis (Thesis Integrated)
        if lid == "OPEN":
            # Dynamic risk classification based on safety threshold
            if temp > 5.5:
                risk_title = "☣️ CRITICAL BIO-HAZARD"
                border_color = "#d9534f"  # Red
                contamination_status = f"<b>HIGH RISK!</b> Capsule temperature ({temp}°C) is in the danger zone while exposed. Rapid microbial multiplication and pathogen contamination are actively in progress."
            else:
                risk_title = "⚠️ WARNING: PATHOGEN VULNERABILITY DETECTED"
                border_color = "#f0ad4e"  # Orange
                contamination_status = f"<b>MODERATE RISK.</b> Temperature is currently stable at {temp}°C, but atmospheric exposure introduces an immediate risk of air-borne bacterial contamination."

            if not bacterial_alert_sent:
                email_subject = f"{risk_title}: Cold-Chain Integrity Compromised!"
                email_body = f"""
                <div style="border-left: 4px solid {border_color}; padding-left: 15px; background-color: #fffcf8; padding: 15px; border-radius: 4px;">
                    <h3 style="color: {border_color}; margin-top: 0;">⚡ PharmaGuard AI Bio-Shield Security Matrix</h3>
                    An unauthorized <b>Lid Opening Event</b> has been captured at [{timestamp}].<br><br>
                    • <b>Current Temperature:</b> {temp}°C<br>
                    • <b>Humidity Status:</b> {humidity}%<br>
                    • <b>Microbial Risk Evaluation:</b> {contamination_status}<br><br>
                    • <b>Llama-3 Edge Optimizer Directive:</b> "{advice}"<br><br>
                    <b>Mandatory Protocol:</b> Secure and re-seal the container immediately. If exposure persists, quarantine the entire pharmaceutical batch for a biochemical assay validation.
                </div>
                """
                send_email_alert(email_subject, email_body)
                bacterial_alert_sent = True
                
        elif lid == "CLOSED":
            bacterial_alert_sent = False

        # Sync payload with Firebase Cloud Database
        ref.push({
            "temp": temp,
            "hum": humidity,
            "lid": lid,
            "shock": shock,
            "prediction": prediction,
            "advice": advice,
            "time": timestamp,
            "traffic": traffic
        })

        # --- TELEMETRY TERMINAL OUTPUT ---
        print("-" * 70)
        print(f"✅ [{timestamp}] Temp: {temp}°C | Hum: {humidity}% | Lid: {lid} | Shock: {shock}G")
        print(f"   ML Prediction: {prediction}°C | Live Dhaka Traffic: {traffic}")
        print(f"   AI Agent Output: \"{advice}\"")
        
        time.sleep(30)

except KeyboardInterrupt:
    print("\n🛑 PharmaGuard Telemetry Shield Safely Shutting Down...")